import thaiTofu from "@/assets/thai-tofu.jpg";
import kungPao from "@/assets/kung-pao.jpg";
import mexicanChicken from "@/assets/mexican-chicken.jpg";
import eggWhite from "@/assets/egg-white-bites.jpg";
import greekFaro from "@/assets/greek-faro.jpg";
import mediterranean from "@/assets/mediterranean.jpg";
import cookies from "@/assets/cookies.jpg";
import cupcake from "@/assets/cupcake.jpg";
import ryeBread from "@/assets/rye-bread.jpg";

export type Recipe = {
  id: string;
  title: string;
  image: string;
  section: "Cusines" | "Diet" | "Bakery";
  cuisine: string;
  price: number;
  minutes: number;
  comments: number;
  likes: number;
  rating: number;
  difficulty: string;
  diet: string[];
  allergies: string[];
  goals: string[];
  description: string;
  ingredients: string[];
  steps: string[];
  nutrition: { label: string; value: string }[];
};

export const recipes: Recipe[] = [
  {
    id: "thai-basil-tofu-stir-fry",
    title: "Thai Basil Tofu Stir Fry",
    image: thaiTofu,
    section: "Cusines",
    cuisine: "Thai",
    price: 123,
    minutes: 30,
    comments: 35,
    likes: 55,
    rating: 4,
    difficulty: "Super Dry",
    diet: ["Dairy Free", "Sugar Free"],
    allergies: ["Legumes"],
    goals: ["Weight loss", "Freshness"],
    description:
      "Fragrant Thai street-food classic: crisp tofu cubes tossed with sweet peppers and a handful of holy basil in a glossy garlic sauce.",
    ingredients: [
      "400g firm tofu, cubed",
      "2 bell peppers, sliced",
      "3 garlic cloves, minced",
      "1 cup Thai basil leaves",
      "2 tbsp soy sauce",
      "1 tbsp rice vinegar",
    ],
    steps: [
      "Press the tofu for 10 minutes, then cube and pan-fry until golden on all sides.",
      "Stir-fry garlic and peppers over high heat for 2 minutes.",
      "Return the tofu, add soy sauce and vinegar, toss for 1 minute.",
      "Kill the heat, fold in the basil and serve with jasmine rice.",
    ],
    nutrition: [
      { label: "Calories", value: "420 kcal" },
      { label: "Protein", value: "24 g" },
      { label: "Carbs", value: "31 g" },
      { label: "Fat", value: "19 g" },
    ],
  },
  {
    id: "kung-pao-shrimp",
    title: "Kung Pao Shrimp",
    image: kungPao,
    section: "Cusines",
    cuisine: "Chines",
    price: 123,
    minutes: 30,
    comments: 35,
    likes: 55,
    rating: 4,
    difficulty: "Super Dry",
    diet: ["Dairy Free", "Gluten Free"],
    allergies: ["Grain"],
    goals: ["Rich Nutritions"],
    description:
      "Sichuan-style shrimp with blistered peppers, scallions and a sweet-hot sauce that clings to every bite.",
    ingredients: [
      "500g shrimp, peeled",
      "2 peppers, chunked",
      "4 dried chillies",
      "3 spring onions",
      "2 tbsp soy sauce",
      "1 tsp cornstarch",
    ],
    steps: [
      "Toss shrimp with cornstarch and a pinch of salt.",
      "Sear the shrimp 1 minute per side, then remove.",
      "Fry chillies and peppers until charred at the edges.",
      "Add sauce, return shrimp, glaze and scatter scallions.",
    ],
    nutrition: [
      { label: "Calories", value: "380 kcal" },
      { label: "Protein", value: "38 g" },
      { label: "Carbs", value: "18 g" },
      { label: "Fat", value: "14 g" },
    ],
  },
  {
    id: "mexican-chicken",
    title: "Mexican Chicken",
    image: mexicanChicken,
    section: "Cusines",
    cuisine: "Italian",
    price: 123,
    minutes: 40,
    comments: 80,
    likes: 100,
    rating: 5,
    difficulty: "Super Dry",
    diet: ["Gluten Free"],
    allergies: ["Glutten"],
    goals: ["Activeness"],
    description:
      "Baked chicken breasts smothered in a smoky cheese sauce, finished with fresh coriander. Weeknight comfort in one dish.",
    ingredients: [
      "4 chicken breasts",
      "200g grated cheese",
      "1 cup salsa",
      "1 tsp smoked paprika",
      "Fresh coriander",
    ],
    steps: [
      "Season the chicken with paprika, salt and pepper.",
      "Sear 2 minutes per side in a hot oven-safe dish.",
      "Spoon over salsa, blanket with cheese.",
      "Bake at 200°C for 20 minutes and top with coriander.",
    ],
    nutrition: [
      { label: "Calories", value: "540 kcal" },
      { label: "Protein", value: "46 g" },
      { label: "Carbs", value: "9 g" },
      { label: "Fat", value: "32 g" },
    ],
  },
  {
    id: "egg-white-bites",
    title: "Egg White Bites",
    image: eggWhite,
    section: "Diet",
    cuisine: "Asian",
    price: 123,
    minutes: 10,
    comments: 80,
    likes: 100,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Sugar Free", "Dairy Free"],
    allergies: ["Fruite"],
    goals: ["Weight loss"],
    description:
      "Ten-minute protein plate: jammy eggs over crunchy lettuce with toasted croutons and a squeeze of lemon.",
    ingredients: [
      "4 eggs",
      "1 head of lettuce",
      "1 cup croutons",
      "1 lemon",
      "Olive oil, salt, pepper",
    ],
    steps: [
      "Boil the eggs for 7 minutes, then cool in ice water.",
      "Tear the lettuce and dress with oil, lemon, salt.",
      "Halve the eggs and arrange on top.",
      "Finish with croutons and cracked pepper.",
    ],
    nutrition: [
      { label: "Calories", value: "260 kcal" },
      { label: "Protein", value: "20 g" },
      { label: "Carbs", value: "12 g" },
      { label: "Fat", value: "15 g" },
    ],
  },
  {
    id: "greek-faro-salad",
    title: "Greek Faro Salad",
    image: greekFaro,
    section: "Diet",
    cuisine: "Italian",
    price: 123,
    minutes: 15,
    comments: 80,
    likes: 100,
    rating: 4,
    difficulty: "Super Dry",
    diet: ["Dairy Free", "Egg Free"],
    allergies: ["Grain"],
    goals: ["Freshness", "Rich Nutritions"],
    description:
      "Chewy farro with chickpeas, tomato and cucumber under a honey-mustard dressing. Better on day two.",
    ingredients: [
      "1 cup cooked farro",
      "1 tin chickpeas",
      "2 tomatoes, diced",
      "1 cucumber, diced",
      "2 tbsp honey mustard dressing",
    ],
    steps: [
      "Cook the farro until al dente and cool it down.",
      "Fold in chickpeas and chopped vegetables.",
      "Pour over the dressing and toss well.",
      "Rest 10 minutes so the grains drink the dressing.",
    ],
    nutrition: [
      { label: "Calories", value: "410 kcal" },
      { label: "Protein", value: "17 g" },
      { label: "Carbs", value: "58 g" },
      { label: "Fat", value: "11 g" },
    ],
  },
  {
    id: "mediterranian-diet-snack",
    title: "Mediterranian Diet Snack",
    image: mediterranean,
    section: "Diet",
    cuisine: "Italian",
    price: 123,
    minutes: 30,
    comments: 80,
    likes: 100,
    rating: 5,
    difficulty: "Super Dry",
    diet: ["Egg Free", "Sugar Free"],
    allergies: ["Glutten"],
    goals: ["Freshness"],
    description:
      "Toasted sourdough loaded with tomatoes, feta and oregano — the fastest way to eat like the coast.",
    ingredients: [
      "2 slices sourdough",
      "150g feta",
      "2 tomatoes",
      "Handful of basil",
      "Oregano and olive oil",
    ],
    steps: [
      "Toast the bread until deeply golden.",
      "Layer basil leaves and sliced tomatoes.",
      "Crumble feta generously over the top.",
      "Drizzle olive oil, dust with oregano.",
    ],
    nutrition: [
      { label: "Calories", value: "330 kcal" },
      { label: "Protein", value: "14 g" },
      { label: "Carbs", value: "28 g" },
      { label: "Fat", value: "18 g" },
    ],
  },
  {
    id: "oat-raisin-cookies",
    title: "Oat & Raisin Cookies",
    image: cookies,
    section: "Bakery",
    cuisine: "Asian",
    price: 123,
    minutes: 25,
    comments: 40,
    likes: 90,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Egg Free"],
    allergies: ["Glutten", "Grain"],
    goals: ["Activeness"],
    description:
      "Chewy centres, crisp edges, plump raisins. The cookie that disappears before it cools.",
    ingredients: [
      "150g rolled oats",
      "120g flour",
      "100g butter",
      "90g brown sugar",
      "80g raisins",
    ],
    steps: [
      "Cream butter and sugar until pale.",
      "Fold in oats, flour and raisins.",
      "Scoop onto parchment, leaving space to spread.",
      "Bake 12 minutes at 180°C, cool on the tray.",
    ],
    nutrition: [
      { label: "Calories", value: "190 kcal" },
      { label: "Protein", value: "3 g" },
      { label: "Carbs", value: "26 g" },
      { label: "Fat", value: "9 g" },
    ],
  },
  {
    id: "chocolate-rose-cupcake",
    title: "Chocolate Rose Cupcake",
    image: cupcake,
    section: "Bakery",
    cuisine: "Thai",
    price: 123,
    minutes: 45,
    comments: 60,
    likes: 120,
    rating: 5,
    difficulty: "Medium",
    diet: ["Gluten Free"],
    allergies: ["Glutten"],
    goals: ["Rich Nutritions"],
    description:
      "Dark cocoa sponge crowned with a piped buttercream rose — the birthday-table showpiece.",
    ingredients: [
      "180g flour",
      "60g cocoa powder",
      "200g sugar",
      "2 eggs",
      "250g butter for the frosting",
      "Pink food colouring",
    ],
    steps: [
      "Whisk the dry ingredients, then beat in eggs and milk.",
      "Fill liners two-thirds full, bake 20 minutes at 175°C.",
      "Whip butter with icing sugar until light.",
      "Pipe a rose from the centre outward and chill briefly.",
    ],
    nutrition: [
      { label: "Calories", value: "410 kcal" },
      { label: "Protein", value: "5 g" },
      { label: "Carbs", value: "48 g" },
      { label: "Fat", value: "23 g" },
    ],
  },
  {
    id: "rye-oat-bread",
    title: "Rye & Oat Bread",
    image: ryeBread,
    section: "Bakery",
    cuisine: "Chines",
    price: 123,
    minutes: 90,
    comments: 25,
    likes: 70,
    rating: 4,
    difficulty: "Medium",
    diet: ["Dairy Free", "Sugar Free"],
    allergies: ["Glutten", "Grain"],
    goals: ["Rich Nutritions", "Activeness"],
    description:
      "A dense, nutty loaf with an oat-strewn crust. Slice it thick, toast it hard, butter it well.",
    ingredients: [
      "300g rye flour",
      "200g bread flour",
      "7g dry yeast",
      "350ml warm water",
      "Rolled oats for the crust",
    ],
    steps: [
      "Mix, then knead 10 minutes until springy.",
      "Prove covered for 60 minutes until doubled.",
      "Shape, roll the top in oats, prove 20 more minutes.",
      "Bake 40 minutes at 210°C with steam.",
    ],
    nutrition: [
      { label: "Calories", value: "220 kcal" },
      { label: "Protein", value: "7 g" },
      { label: "Carbs", value: "42 g" },
      { label: "Fat", value: "2 g" },
    ],
  },
  // Additional Cuisine Recipes
  {
    id: "italian-margherita-pizza",
    title: "Classic Italian Margherita Pizza",
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80",
    section: "Cusines",
    cuisine: "Italian",
    price: 140,
    minutes: 25,
    comments: 64,
    likes: 145,
    rating: 5,
    difficulty: "Medium",
    diet: ["Egg Free"],
    allergies: ["Glutten", "Grain"],
    goals: ["Rich Nutritions", "Freshness"],
    description:
      "Authentic Neapolitan pizza topped with crushed San Marzano tomatoes, fresh mozzarella, fragrant basil leaves, and extra virgin olive oil.",
    ingredients: [
      "250g pizza dough",
      "100g San Marzano tomato sauce",
      "125g fresh mozzarella cheese",
      "Fresh basil leaves",
      "1 tbsp extra virgin olive oil",
      "Pinch of sea salt",
    ],
    steps: [
      "Stretch dough into a 12-inch circle on a floured surface.",
      "Spread tomato sauce evenly, leaving a crust border.",
      "Tear fresh mozzarella over the sauce.",
      "Bake at 250°C (480°F) for 10-12 minutes until crust is golden and cheese is bubbly.",
      "Scatter fresh basil and drizzle with olive oil before serving.",
    ],
    nutrition: [
      { label: "Calories", value: "580 kcal" },
      { label: "Protein", value: "22 g" },
      { label: "Carbs", value: "72 g" },
      { label: "Fat", value: "22 g" },
    ],
  },
  {
    id: "sichuan-dan-dan-noodles",
    title: "Spicy Sichuan Dan Dan Noodles",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    section: "Cusines",
    cuisine: "Chines",
    price: 110,
    minutes: 20,
    comments: 48,
    likes: 112,
    rating: 5,
    difficulty: "Medium",
    diet: ["Dairy Free"],
    allergies: ["Glutten", "Legumes"],
    goals: ["Activeness"],
    description:
      "Savory, fiery Chinese street noodles coated in a rich sesame chili oil sauce, topped with crispy spiced minced meat and preserved mustard greens.",
    ingredients: [
      "300g wheat noodles",
      "200g minced meat",
      "2 tbsp chili oil with flakes",
      "2 tbsp sesame paste",
      "1 tbsp soy sauce",
      "Sichuan pepper powder",
      "Chopped scallions and peanuts",
    ],
    steps: [
      "Boil noodles until al dente, drain and divide into bowls.",
      "Stir-fry minced meat with soy sauce and Sichuan pepper until crispy.",
      "Whisk sesame paste, chili oil, soy sauce, and warm broth into a smooth sauce base.",
      "Pour sauce over noodles, top with crispy meat, scallions, and crushed peanuts.",
    ],
    nutrition: [
      { label: "Calories", value: "520 kcal" },
      { label: "Protein", value: "26 g" },
      { label: "Carbs", value: "62 g" },
      { label: "Fat", value: "20 g" },
    ],
  },
  {
    id: "pad-thai-shrimp",
    title: "Authentic Pad Thai Shrimp",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80",
    section: "Cusines",
    cuisine: "Thai",
    price: 135,
    minutes: 25,
    comments: 52,
    likes: 130,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Dairy Free", "Gluten Free"],
    allergies: ["Legumes"],
    goals: ["Freshness", "Activeness"],
    description:
      "Vibrant Thai stir-fried rice noodles with plump shrimp, tofu, bean sprouts, crushed peanuts, and tangy tamarind lime glaze.",
    ingredients: [
      "200g flat rice noodles",
      "250g succulent shrimp",
      "2 tbsp tamarind paste",
      "1 tbsp fish sauce",
      "1 cup bean sprouts",
      "2 eggs, scrambled",
      "Lime wedges & crushed peanuts",
    ],
    steps: [
      "Soak rice noodles in warm water until pliable.",
      "Sear shrimp in a screaming hot wok for 2 minutes, set aside.",
      "Scramble eggs, add noodles and tamarind sauce, tossing vigorously.",
      "Fold in bean sprouts, shrimp, and serve with fresh lime and peanuts.",
    ],
    nutrition: [
      { label: "Calories", value: "490 kcal" },
      { label: "Protein", value: "32 g" },
      { label: "Carbs", value: "55 g" },
      { label: "Fat", value: "15 g" },
    ],
  },
  {
    id: "creamy-tuscan-salmon",
    title: "Creamy Tuscan Garlic Salmon",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80",
    section: "Cusines",
    cuisine: "Italian",
    price: 175,
    minutes: 35,
    comments: 92,
    likes: 210,
    rating: 5,
    difficulty: "Medium",
    diet: ["Gluten Free", "Sugar Free"],
    allergies: [],
    goals: ["Rich Nutritions", "Weight loss"],
    description:
      "Pan-seared crisp salmon fillets simmering in a velvety garlic cream sauce loaded with sun-dried tomatoes and baby spinach.",
    ingredients: [
      "4 salmon fillets",
      "1 cup heavy cream",
      "1/2 cup sun-dried tomatoes",
      "2 cups fresh baby spinach",
      "4 cloves garlic, minced",
      "Parmesan cheese",
    ],
    steps: [
      "Sear salmon fillets 4 minutes per side until golden brown, remove.",
      "Sauté garlic and sun-dried tomatoes in the pan juices.",
      "Pour cream, bring to a simmer, and stir in spinach and parmesan.",
      "Return salmon fillets to sauce and simmer for 3 minutes before serving.",
    ],
    nutrition: [
      { label: "Calories", value: "610 kcal" },
      { label: "Protein", value: "42 g" },
      { label: "Carbs", value: "10 g" },
      { label: "Fat", value: "44 g" },
    ],
  },
  {
    id: "teriyaki-salmon-bowl",
    title: "Teriyaki Glazed Salmon Bowl",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    section: "Cusines",
    cuisine: "Asian",
    price: 160,
    minutes: 25,
    comments: 71,
    likes: 185,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Dairy Free"],
    allergies: ["Grain"],
    goals: ["Rich Nutritions", "Freshness"],
    description:
      "Sweet and sticky teriyaki salmon served over steamed sushi rice with cucumber, avocado, and toasted sesame seeds.",
    ingredients: [
      "2 salmon fillets",
      "3 tbsp teriyaki glaze",
      "1 cup steamed sushi rice",
      "1 avocado, sliced",
      "1 cucumber, ribboned",
      "Sesame seeds & nori strips",
    ],
    steps: [
      "Pan-sear salmon fillets and brush generously with teriyaki glaze.",
      "Assemble steamed rice in serving bowls.",
      "Top with glazed salmon, avocado slices, and cucumber ribbons.",
      "Garnish with sesame seeds and crispy nori.",
    ],
    nutrition: [
      { label: "Calories", value: "540 kcal" },
      { label: "Protein", value: "36 g" },
      { label: "Carbs", value: "48 g" },
      { label: "Fat", value: "22 g" },
    ],
  },

  // Additional Diet Recipes
  {
    id: "avocado-greens-detox-bowl",
    title: "Avocado Greens Detox Bowl",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    section: "Diet",
    cuisine: "Asian",
    price: 105,
    minutes: 15,
    comments: 38,
    likes: 95,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Dairy Free", "Egg Free", "Sugar Free", "Gluten Free"],
    allergies: ["Fruite"],
    goals: ["Weight loss", "Freshness"],
    description:
      "Nutrient-dense clean eating bowl packed with creamy avocado, kale, edamame, cucumber, and lemon tahini dressing.",
    ingredients: [
      "1 ripe avocado, sliced",
      "2 cups curly kale, massaged",
      "1/2 cup shelled edamame",
      "1 cucumber, sliced",
      "2 tbsp lemon tahini dressing",
      "Pumpkin seeds",
    ],
    steps: [
      "Massage kale with a drop of olive oil and sea salt.",
      "Arrange kale, avocado, edamame, and cucumber in a bowl.",
      "Drizzle with lemon tahini dressing.",
      "Top with crunchy pumpkin seeds.",
    ],
    nutrition: [
      { label: "Calories", value: "310 kcal" },
      { label: "Protein", value: "11 g" },
      { label: "Carbs", value: "19 g" },
      { label: "Fat", value: "23 g" },
    ],
  },
  {
    id: "quinoa-berry-power-salad",
    title: "Quinoa Berry Power Salad",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    section: "Diet",
    cuisine: "Italian",
    price: 115,
    minutes: 15,
    comments: 45,
    likes: 108,
    rating: 4,
    difficulty: "Super Easy",
    diet: ["Dairy Free", "Egg Free", "Gluten Free"],
    allergies: ["Fruite"],
    goals: ["Weight loss", "Activeness"],
    description:
      "Fluffy protein-rich quinoa mixed with fresh blueberries, spinach, walnuts, and balsamic citrus vinaigrette.",
    ingredients: [
      "1 cup cooked quinoa",
      "1/2 cup fresh blueberries",
      "2 cups baby spinach",
      "1/4 cup toasted walnuts",
      "2 tbsp balsamic vinaigrette",
    ],
    steps: [
      "Fluff cooked quinoa and let cool slightly.",
      "Toss spinach, quinoa, and blueberries together.",
      "Drizzle balsamic dressing and sprinkle toasted walnuts.",
    ],
    nutrition: [
      { label: "Calories", value: "340 kcal" },
      { label: "Protein", value: "9 g" },
      { label: "Carbs", value: "41 g" },
      { label: "Fat", value: "16 g" },
    ],
  },
  {
    id: "keto-lemon-herb-chicken",
    title: "Keto Lemon Herb Chicken Breast",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80",
    section: "Diet",
    cuisine: "Italian",
    price: 150,
    minutes: 30,
    comments: 62,
    likes: 140,
    rating: 5,
    difficulty: "Medium",
    diet: ["Dairy Free", "Sugar Free", "Gluten Free"],
    allergies: [],
    goals: ["Weight loss", "Rich Nutritions"],
    description:
      "Juicy roasted chicken breast marinated in fresh lemon juice, rosemary, garlic, and extra virgin olive oil.",
    ingredients: [
      "2 large chicken breasts",
      "2 tbsp olive oil",
      "1 lemon, zested and juiced",
      "2 sprigs fresh rosemary",
      "3 cloves garlic",
    ],
    steps: [
      "Marinate chicken breasts in lemon juice, olive oil, garlic, and chopped rosemary for 15 minutes.",
      "Sear in a hot pan for 3 minutes per side.",
      "Transfer to oven and roast at 200°C for 18 minutes until juicy and internal temp hits 75°C.",
    ],
    nutrition: [
      { label: "Calories", value: "390 kcal" },
      { label: "Protein", value: "48 g" },
      { label: "Carbs", value: "3 g" },
      { label: "Fat", value: "20 g" },
    ],
  },
  {
    id: "edamame-tofu-buddha-bowl",
    title: "Steamed Edamame & Tofu Buddha Bowl",
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    section: "Diet",
    cuisine: "Asian",
    price: 98,
    minutes: 15,
    comments: 29,
    likes: 88,
    rating: 4,
    difficulty: "Super Easy",
    diet: ["Dairy Free", "Egg Free", "Sugar Free"],
    allergies: ["Legumes"],
    goals: ["Weight loss", "Freshness"],
    description:
      "Light, refreshing vegan bowl with steamed edamame beans, silken tofu, shredded carrots, and ginger-soy drizzle.",
    ingredients: [
      "150g silken tofu",
      "1 cup steamed edamame",
      "1 shredded carrot",
      "1 cup brown rice",
      "1 tbsp low-sodium soy sauce",
      "1 tsp fresh ginger",
    ],
    steps: [
      "Steam edamame for 4 minutes.",
      "Slice silken tofu into neat cubes.",
      "Layer brown rice, edamame, carrots, and tofu.",
      "Drizzle ginger-soy sauce over top.",
    ],
    nutrition: [
      { label: "Calories", value: "350 kcal" },
      { label: "Protein", value: "22 g" },
      { label: "Carbs", value: "42 g" },
      { label: "Fat", value: "10 g" },
    ],
  },
  {
    id: "chia-seed-berry-pudding",
    title: "Chia Seed Berry Parfait",
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    section: "Diet",
    cuisine: "Thai",
    price: 85,
    minutes: 10,
    comments: 51,
    likes: 125,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Dairy Free", "Egg Free", "Sugar Free", "Gluten Free"],
    allergies: ["Fruite"],
    goals: ["Freshness", "Activeness"],
    description:
      "Overnight coconut chia pudding layered with fresh raspberry puree, coconut flakes, and chia crunch.",
    ingredients: [
      "3 tbsp chia seeds",
      "1 cup almond milk",
      "1/2 tsp vanilla extract",
      "1/2 cup fresh raspberries",
      "Toasted coconut flakes",
    ],
    steps: [
      "Whisk chia seeds, almond milk, and vanilla, let soak in fridge.",
      "Mash raspberries into a rough puree.",
      "Layer chia pudding and raspberry puree in a glass vessel.",
      "Garnish with toasted coconut flakes.",
    ],
    nutrition: [
      { label: "Calories", value: "210 kcal" },
      { label: "Protein", value: "6 g" },
      { label: "Carbs", value: "22 g" },
      { label: "Fat", value: "11 g" },
    ],
  },

  // Additional Bakery Recipes
  {
    id: "artisan-sourdough-boule",
    title: "Artisan Sourdough Boule",
    image: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=800&q=80",
    section: "Bakery",
    cuisine: "Italian",
    price: 90,
    minutes: 120,
    comments: 74,
    likes: 160,
    rating: 5,
    difficulty: "Medium",
    diet: ["Dairy Free", "Egg Free", "Sugar Free"],
    allergies: ["Glutten", "Grain"],
    goals: ["Rich Nutritions"],
    description:
      "Crusty round sourdough loaf with an open airy crumb, rich fermentation flavor, and blistered golden crust.",
    ingredients: [
      "400g bread flour",
      "100g whole wheat flour",
      "350g water",
      "100g active sourdough starter",
      "10g fine sea salt",
    ],
    steps: [
      "Autolyse flour and water for 45 minutes.",
      "Mix starter and salt, bulk ferment with stretch & folds every 30 mins for 4 hours.",
      "Shape into a round boule and proof in banneton overnight.",
      "Bake in Dutch oven at 240°C for 20 mins covered, then 20 mins uncovered.",
    ],
    nutrition: [
      { label: "Calories", value: "210 kcal" },
      { label: "Protein", value: "8 g" },
      { label: "Carbs", value: "43 g" },
      { label: "Fat", value: "1 g" },
    ],
  },
  {
    id: "french-butter-croissants",
    title: "French Butter Croissants",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    section: "Bakery",
    cuisine: "Italian",
    price: 110,
    minutes: 60,
    comments: 115,
    likes: 230,
    rating: 5,
    difficulty: "Medium",
    diet: ["Egg Free"],
    allergies: ["Glutten", "Grain"],
    goals: ["Freshness"],
    description:
      "Golden, flaky, buttery laminated croissants with paper-thin crisp layers and a melt-in-your-mouth interior.",
    ingredients: [
      "500g pastry flour",
      "250g French butter block",
      "10g instant yeast",
      "50g sugar",
      "10g salt",
      "Egg wash for shine",
    ],
    steps: [
      "Prepare yeast dough and chill for 2 hours.",
      "Laminate butter block into dough with 3 letter turns.",
      "Roll out, cut triangles, and roll tightly into croissant crescents.",
      "Proof for 2 hours, brush with egg wash, bake at 200°C for 18 minutes.",
    ],
    nutrition: [
      { label: "Calories", value: "340 kcal" },
      { label: "Protein", value: "5 g" },
      { label: "Carbs", value: "32 g" },
      { label: "Fat", value: "21 g" },
    ],
  },
  {
    id: "blueberry-lemon-muffins",
    title: "Blueberry Lemon Bakery Muffins",
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80",
    section: "Bakery",
    cuisine: "Asian",
    price: 95,
    minutes: 30,
    comments: 43,
    likes: 118,
    rating: 5,
    difficulty: "Super Easy",
    diet: ["Gluten Free"],
    allergies: ["Fruite", "Glutten"],
    goals: ["Activeness", "Freshness"],
    description:
      "Tall, dome-topped muffins bursting with juicy fresh blueberries, lemon zest, and a crunchy coarse sugar topping.",
    ingredients: [
      "250g gluten-free flour",
      "150g fresh blueberries",
      "1 lemon zest and juice",
      "100g sugar",
      "2 eggs",
      "80ml vegetable oil",
    ],
    steps: [
      "Whisk wet and dry ingredients separately, then gently fold together.",
      "Fold in blueberries carefully to avoid bleeding color.",
      "Scoop into muffin tins, sprinkle coarse sugar on top.",
      "Bake at 200°C for 20 minutes until golden and springy.",
    ],
    nutrition: [
      { label: "Calories", value: "270 kcal" },
      { label: "Protein", value: "4 g" },
      { label: "Carbs", value: "38 g" },
      { label: "Fat", value: "11 g" },
    ],
  },
  {
    id: "matcha-green-tea-tart",
    title: "Matcha Green Tea Tart",
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
    section: "Bakery",
    cuisine: "Asian",
    price: 130,
    minutes: 40,
    comments: 56,
    likes: 142,
    rating: 5,
    difficulty: "Medium",
    diet: ["Sugar Free"],
    allergies: ["Grain"],
    goals: ["Rich Nutritions", "Freshness"],
    description:
      "Velvety Uji matcha ganache poured into a crisp sweet pastry shell, garnished with white chocolate dust.",
    ingredients: [
      "1 sweet tart crust",
      "200g white chocolate",
      "100ml heavy cream",
      "2 tbsp ceremonial Uji matcha powder",
      "1 tbsp butter",
    ],
    steps: [
      "Blind bake tart crust until golden, let cool completely.",
      "Heat cream, pour over chopped white chocolate and whisk until smooth.",
      "Sift matcha powder into cream ganache and blend till vibrant green.",
      "Pour into tart shell and chill in fridge for 3 hours until set.",
    ],
    nutrition: [
      { label: "Calories", value: "380 kcal" },
      { label: "Protein", value: "6 g" },
      { label: "Carbs", value: "35 g" },
      { label: "Fat", value: "24 g" },
    ],
  },
  {
    id: "cinnamon-cardamom-rolls",
    title: "Cinnamon & Cardamom Rolls",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    section: "Bakery",
    cuisine: "Thai",
    price: 105,
    minutes: 50,
    comments: 68,
    likes: 175,
    rating: 5,
    difficulty: "Medium",
    diet: ["Egg Free"],
    allergies: ["Glutten"],
    goals: ["Activeness"],
    description:
      "Soft, pillowy Swedish-style yeast rolls swirled with fragrant cinnamon, crushed cardamom, and pearl sugar glaze.",
    ingredients: [
      "400g bread flour",
      "7g instant yeast",
      "75g butter",
      "2 tsp crushed cardamom",
      "2 tbsp cinnamon",
      "100g brown sugar",
      "Pearl sugar for topping",
    ],
    steps: [
      "Knead soft yeast dough infused with crushed cardamom, prove 1 hour.",
      "Roll dough into rectangle, spread butter, cinnamon, and brown sugar.",
      "Roll up, slice into rounds, and arrange in baking dish.",
      "Proof 30 mins, top with pearl sugar, bake at 190°C for 22 mins.",
    ],
    nutrition: [
      { label: "Calories", value: "320 kcal" },
      { label: "Protein", value: "6 g" },
      { label: "Carbs", value: "46 g" },
      { label: "Fat", value: "12 g" },
    ],
  },
];

export const filterGroups = {
  Diet: ["Dairy Free", "Egg Free", "Sugar Free", "Gluten Free"],
  Allergies: ["Glutten", "Legumes", "Grain", "Fruite"],
  Cusine: ["Asian", "Italian", "Chines", "Thai"],
  Goals: ["Weight loss", "Freshness", "Activeness", "Rich Nutritions"],
} as const;

export type FilterState = {
  Diet: string[];
  Allergies: string[];
  Cusine: string[];
  Goals: string[];
};

export const emptyFilters: FilterState = {
  Diet: [],
  Allergies: [],
  Cusine: [],
  Goals: [],
};

export function getRecipe(id: string) {
  return recipes.find((r) => r.id === id);
}

export function filterRecipes(filters: FilterState, query: string) {
  const q = query.trim().toLowerCase();
  return recipes.filter((r) => {
    if (q && !`${r.title} ${r.cuisine} ${r.description}`.toLowerCase().includes(q)) {
      return false;
    }
    if (filters.Diet.length && !filters.Diet.some((f) => r.diet.includes(f))) return false;
    if (filters.Allergies.length && !filters.Allergies.some((f) => r.allergies.includes(f)))
      return false;
    if (filters.Cusine.length && !filters.Cusine.includes(r.cuisine)) return false;
    if (filters.Goals.length && !filters.Goals.some((f) => r.goals.includes(f))) return false;
    return true;
  });
}
